### ISSUE TITLE
Failure when running vagrant up

### ISSUE THREAD

**Issue by jerrywardlow** [Rickymare/playbook-wordpress#3]
When I clone the repo and run `vagrant up` from the master branch, I get an error when Ansible runs:
```
 _______________________
< TASK [Install Apache] >
 -----------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [default]: FAILED! => {
    "cache_update_time": 1513201319,
    "cache_updated": false, 
    "changed": false, 
    "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'apache2'' failed: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)\nE: Unable to lock the administration directory (/var/lib/dpkg/), are you root?\n",
    "rc": 100,
    "stderr": "E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)\nE: Unable to lock the administration directory (/var/lib/dpkg/), are you root?\n", 
    "stderr_lines": ["E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)", "E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?"], 
    "stdout": "", 
    "stdout_lines": []
}
```
I think we worked through a solution to this today, can you fix it?

**Comment by Rickymare** [comment]
Fixed it

**Comment by jerrywardlow** [comment]
I ran `git pull` on the `master` branch and it doesn't say there any changes. The bug is still there when I run `vagrant up`.

**Comment by Rickymare** [comment]
Hey Jerry, thanks for the response. Could you try running vagrant provision, again? I think I fixed it

**Comment by jerrywardlow** [comment]
Yeah it works now. Next time you have an issue if you create a PR that fixes it (wink wink nudge nudge) you can say stuff like `Fixes #3` (the number of the issue) and GitHub will automatically close the issue when the PR is merged to master.
